language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - phpunit

after_script:

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
