language: php

addons:
    chrome: stable

php:
    - 7.3
    - 7.4
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - phpunit

cache:
    directories:
        - vendor
        - $COMPOSER_CACHE_DIR
