language: php

addons:
    chrome: stable

php:
    - 7.4snapshot
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
    - travis_retry composer self-update
    - echo $TRAVIS_PHP_VERSION
    - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]] ; then travis_retry composer install --no-interaction --prefer-dist ; fi
    - if [[ $TRAVIS_PHP_VERSION == nightly ]] ; then travis_retry composer install --no-interaction --prefer-dist --configuration tests/php8-composer.json ; fi

script:
    - vendor/bin/simple-phpunit

cache:
    directories:
        - vendor
        - $COMPOSER_CACHE_DIR
